var P8CONFIG = {
		url: 'https://bsdt.gdsdxy.edu.cn',
		RESOURCE: 'https://bsdt.gdsdxy.edu.cn',
		language: 'zh-cn',
		controller: 'https://bsdt.gdsdxy.edu.cn/index.php',
		U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php',
		cookie_prefix: 'bsdtss1_',
		cookie_path: '/',
		base_domain: 'gdsdxy.edu.cn',
		mobile_status: 1,
		mobile_auto_jump: 1,
		mobile_url: 'https://bsdt.gdsdxy.edu.cn/m',
		
	URI: {
		'ask': {'': {url: 'https://bsdt.gdsdxy.edu.cn/ask',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/ask',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/ask'},
			'answer': {url: 'https://bsdt.gdsdxy.edu.cn/ask/modules/answer',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/ask/answer',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/ask/answer'},
			'category': {url: 'https://bsdt.gdsdxy.edu.cn/ask/modules/category',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/ask/category',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/ask/category'},
			'item': {url: 'https://bsdt.gdsdxy.edu.cn/ask/modules/item',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/ask/item',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/ask/item'},
			'member': {url: 'https://bsdt.gdsdxy.edu.cn/ask/modules/member',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/ask/member',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/ask/member'}
		},
		'cms': {'': {url: 'https://bsdt.gdsdxy.edu.cn/cms',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cms',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cms'},
			'assist_category': {url: 'https://bsdt.gdsdxy.edu.cn/cms/modules/assist_category',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cms/assist_category',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cms/assist_category'},
			'category': {url: 'https://bsdt.gdsdxy.edu.cn/cms/modules/category',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cms/category',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cms/category'},
			'item': {url: 'https://bsdt.gdsdxy.edu.cn/cms/modules/item',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cms/item',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cms/item'},
			'model': {url: 'https://bsdt.gdsdxy.edu.cn/cms/modules/model',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cms/model',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cms/model'},
			'statistic': {url: 'https://bsdt.gdsdxy.edu.cn/cms/modules/statistic',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cms/statistic',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cms/statistic'},
			'wechat': {url: 'https://bsdt.gdsdxy.edu.cn/cms/modules/wechat',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cms/wechat',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cms/wechat'}
		},
		'sites': {'': {url: 'https://bsdt.gdsdxy.edu.cn/sites',controller: 'https://bsdt.gdsdxy.edu.cn/s.php/slfzjjh',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sites'},
			'category': {url: 'https://bsdt.gdsdxy.edu.cn/sites/modules/category',controller: 'https://bsdt.gdsdxy.edu.cn/s.php/slfzjjh/category',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sites/category'},
			'farm': {url: 'https://bsdt.gdsdxy.edu.cn/sites/modules/farm',controller: 'https://bsdt.gdsdxy.edu.cn/s.php/slfzjjh/farm',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sites/farm'},
			'item': {url: 'https://bsdt.gdsdxy.edu.cn/sites/modules/item',controller: 'https://bsdt.gdsdxy.edu.cn/s.php/slfzjjh/item',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sites/item'},
			'letter': {url: 'https://bsdt.gdsdxy.edu.cn/sites/modules/letter',controller: 'https://bsdt.gdsdxy.edu.cn/s.php/slfzjjh/letter',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sites/letter'},
			'model': {url: 'https://bsdt.gdsdxy.edu.cn/sites/modules/model',controller: 'https://bsdt.gdsdxy.edu.cn/s.php/slfzjjh/model',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sites/model'},
			'stop': {url: 'https://bsdt.gdsdxy.edu.cn/sites/modules/stop',controller: 'https://bsdt.gdsdxy.edu.cn/s.php/slfzjjh/stop',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sites/stop'}
		},
		core: {'': {url: 'https://bsdt.gdsdxy.edu.cn',controller: 'https://bsdt.gdsdxy.edu.cn/index.php'},
			'46': {url: 'https://bsdt.gdsdxy.edu.cn/modules/46',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/46',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/46'},
			'credit': {url: 'https://bsdt.gdsdxy.edu.cn/modules/credit',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/credit',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/credit'},
			'crontab': {url: 'https://bsdt.gdsdxy.edu.cn/modules/crontab',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/crontab',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/crontab'},
			'cservice': {url: 'https://bsdt.gdsdxy.edu.cn/modules/cservice',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/cservice',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/cservice'},
			'dbm': {url: 'https://bsdt.gdsdxy.edu.cn/modules/dbm',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/dbm',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/dbm'},
			'discuzx': {url: '',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/discuzx',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/discuzx'},
			'forms': {url: 'https://bsdt.gdsdxy.edu.cn/modules/forms',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/forms',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/forms'},
			'friendlink': {url: 'https://bsdt.gdsdxy.edu.cn/modules/friendlink',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/friendlink',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/friendlink'},
			'guestbook': {url: 'https://bsdt.gdsdxy.edu.cn/modules/guestbook',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/guestbook',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/guestbook'},
			'interview': {url: 'https://bsdt.gdsdxy.edu.cn/modules/interview',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/interview',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/interview'},
			'label': {url: 'https://bsdt.gdsdxy.edu.cn/modules/label',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/label',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/label'},
			'letter': {url: 'https://bsdt.gdsdxy.edu.cn/modules/letter',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/letter',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/letter'},
			'mail': {url: 'https://bsdt.gdsdxy.edu.cn/modules/mail',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/mail',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/mail'},
			'member': {url: 'https://bsdt.gdsdxy.edu.cn/modules/member',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/member',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/member'},
			'message': {url: 'https://bsdt.gdsdxy.edu.cn/modules/message',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/message',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/message'},
			'notify': {url: 'https://bsdt.gdsdxy.edu.cn/modules/notify',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/notify',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/notify'},
			'page': {url: 'https://bsdt.gdsdxy.edu.cn/modules/page',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/page',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/page'},
			'pay': {url: 'https://bsdt.gdsdxy.edu.cn/modules/pay',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/pay',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/pay'},
			'role': {url: 'https://bsdt.gdsdxy.edu.cn/modules/role',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/role',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/role'},
			'shortcutsms': {url: 'https://bsdt.gdsdxy.edu.cn/modules/shortcutsms',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/shortcutsms',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/shortcutsms'},
			'sms': {url: 'https://bsdt.gdsdxy.edu.cn/modules/sms',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/sms',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/sms'},
			'special': {url: 'https://bsdt.gdsdxy.edu.cn/modules/special',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/special',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/special'},
			'spider': {url: 'https://bsdt.gdsdxy.edu.cn/modules/spider',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/spider',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/spider'},
			'survey': {url: 'https://bsdt.gdsdxy.edu.cn/modules/survey',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/survey',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/survey'},
			'uchome': {url: '',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/uchome',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/uchome'},
			'uploader': {url: 'https://bsdt.gdsdxy.edu.cn/modules/uploader',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/uploader',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/uploader'},
			'vote': {url: 'https://bsdt.gdsdxy.edu.cn/modules/vote',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/vote',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/vote'},
			'xspace': {url: 'https://bsdt.gdsdxy.edu.cn/modules/xspace',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/xspace',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/xspace'},
			'opinion': {url: 'https://bsdt.gdsdxy.edu.cn/modules/opinion',controller: 'https://bsdt.gdsdxy.edu.cn/index.php/opinion',U_controller: 'https://bsdt.gdsdxy.edu.cn/u.php/opinion'}
		}
	}
	};