// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.


$(document).ready(function () {
	

	// 菜单伸缩
	$(".btn1").click(function () {
		if ($(".zhezhao").hasClass('zopen')) {
			if ($(".btn1").hasClass("open")) {
				$(".zhezhao").removeClass('zopen');	
				} else {
					$(".zhezhao").addClass('zopen');		
				}
			}
			else {
				$(".zhezhao").addClass('zopen');
			}
		
		$("#list1").addClass("open");
		$("#list2").removeClass("open");
		$("#list3").removeClass("open");
		$("#list5").removeClass("open");
		
		if ($(".btn1").hasClass("open")) {
				$(".btn1").removeClass("open");
			} else {
				$(".btn1").addClass("open");	
			}
			
		$(".btn2").removeClass("open");
		$(".btn3").removeClass("open");
		$(".btn4").removeClass("open");
		$(".btn5").removeClass("open");
		
	});
	
	
	   
	 //我的收藏 点赞  $(this).siblings().removeClass("open");
	$('.wd-btn-sc').click(function() {				
		if ($(this).hasClass('act')) {
			$(this).removeClass('act');	
			
		} else {
			$(this).addClass('act');
		}
	});
	
	
	// 返回顶部
	$('#totop').click(function () {
		$('html,body').animate({ scrollTop: 0 }, 300);
	});

	
	
	// 目录
	$('.title').click(function () {
		$(this).parent(".mulu").toggleClass('open');
    });
		
	$('.article-title .icon').click(function () {
		$(this).toggleClass('on');
    });
	
	
	
	
	// menu
	$(".menu1").click(function () {
		$(".menu2").removeClass("hov");
		$(".menu3").removeClass("hov");
		$(".menu1").addClass("hov");
		//$("#parallax").addClass("weizhi1");
		
	});
	$(".menu2").click(function () {
		$(".menu1").removeClass("hov");
		$(".menu3").removeClass("hov");
		$(".menu2").addClass("hov");
	});
	$(".menu3").click(function () {
		$(".menu1").removeClass("hov");
		$(".menu2").removeClass("hov");
		$(".menu3").addClass("hov");
	});
	
	
	$(window).scroll( function() { 
		$("#parallax").removeClass("weizhi1");
	});

	
	
});




const checkboxes = document.getElementsByTagName("input");
        const gallery = [{
            title: "丰都",
            description: "照片介绍",
            src: "images/duibi/fengdu1.jpg"
        },{
            title: "丰都旧照",
            description: "照片介绍",
            src: "images/duibi/fengdu2.jpg"
        },{
            title: "长寿",
            description: "照片介绍",
            src: "images/duibi/changshou1.jpg"
        },{
            title: "长寿旧照",
            description: "照片介绍",
            src: "images/duibi/changshou2.jpg"
        },{
            title: "涪陵",
            description: "照片介绍",
            src: "images/duibi/fuling1.jpg"
        },{
            title: "涪陵旧照",
            description: "照片介绍",
            src: "images/duibi/fuling2.jpg"
        },{
            title: "兴山",
            description: "照片介绍",
            src: "images/duibi/xingshan1.jpg"
        },{
            title: "兴山旧照",
            description: "照片介绍",
            src: "images/duibi/xingshan2.jpg"
        },{
            title: "云阳",
            description: "照片介绍",
            src: "images/duibi/yunyang1.jpg"
        },{
            title: "云阳旧照",
            description: "照片介绍",
            src: "images/duibi/yunyang2.jpg"
        },{
            title: "忠县",
            description: "照片介绍",
            src: "images/duibi/zhongxian1.jpg"
        },{
            title: "忠县旧照",
            description: "照片介绍",
            src: "images/duibi/zhongxian2.jpg"
        },{
            title: "开州",
            description: "照片介绍",
            src: "images/duibi/kaizhou1.jpg"
        },{
            title: "开州旧照",
            description: "照片介绍",
            src: "images/duibi/kaizhou2.jpg"
        },{
            title: "万州",
            description: "照片介绍",
            src: "images/duibi/wanzhou1.jpg"
        },{
            title: "万州旧照",
            description: "照片介绍",
            src: "images/duibi/wanzhou2.jpg"
        },{
            title: "奉节",
            description: "照片介绍",
            src: "images/duibi/fengjie1.jpg"
        },{
            title: "奉节旧照",
            description: "照片介绍",
            src: "images/duibi/fengjie2.jpg"
        },{
            title: "巫山",
            description: "照片介绍",
            src: "images/duibi/wushan1.jpg"
        },{
            title: "巫山旧照",
            description: "照片介绍",
            src: "images/duibi/wushan2.jpg"
        },{
            title: "巴东",
            description: "照片介绍",
            src: "images/duibi/badong1.jpg"
        },{
            title: "巴东旧照",
            description: "照片介绍",
            src: "images/duibi/badong2.jpg"
        },{
            title: "秭归",
            description: "照片介绍",
            src: "images/duibi/zigui1.jpg"
        },{
            title: "秭归",
            description: "照片介绍",
            src: "images/duibi/zigui2.jpg"
        }];
		window.showGallery = function(index){
				Spotlight.show(gallery, {
					index: index,
					theme: "dark",
				});
			};
